name: 'npm-dependency-stats-action'
description: 'An action for getting stats about npm dependencies'
author: 'Side Inc.'
inputs:
  working-directory:
    required: false
    description: 'Current working directory'
  output-file:
    required: false
    description: 'Path for output json file'
  log-results:
    required: false
    default: 'false'
    description: 'Whether or not to log dependency info to Github Actions output'
runs:
  using: 'node20'
  main: 'dist/index.js'
