name: 'npm-dependency-stats-action'
description: 'An action for getting stats about npm dependencies'
author: 'Side Inc.'
inputs:
  working-directory:
    required: false
    description: 'Current working directory'
  packages-folder:
    required: false
    default: 'packages'
    description: 'Path to the packages folder'
  output-file:
    required: false
    description: 'Path for output json file'
  is-monorepo:
    required: false
    description: 'Whether or not repo is a monorepo'
  log-results:
    required: false
    default: 'false'
    description: 'Whether or not to log dependency info to Github Actions output'
runs:
  using: 'node20'
  main: 'dist/index.js'
