name: 'npm-dependency-stats-action'
description: 'An action for getting stats about npm dependencies'
author: 'Side Inc.'
inputs:
  working-directory:
    required: false
    description: 'Current working directory'
runs:
  using: 'node12'
  main: 'dist/index.js'