name: Renovate

# NOTE: This workflow is only needed since we are making use of global allowedPostUpgradeCommands
# config option to run build as part of Renovate PRs - needed because dist is part of git tracking
# in order to support Github Actions

on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.81.2
        with:
          configurationFile: ./renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
