name: Renovate

# NOTE: This workflow is only needed since we are making use of global allowedPostUpgradeCommands
# config option to run build as part of Renovate PRs - needed because dist is part of git tracking
# in order to support Github Actions

on:
  workflow_dispatch:
  # schedule:
  #   # The "*" (#42, asterisk) character has special semantics in YAML, so this
  #   # string has to be quoted.
  #   - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/fix-renovate-test-syntax

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.81.2
        with:
          configurationFile: ./renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: 'reside-eng/npm-dependency-stats-action'
          RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
