name: Verify (dependabot)

on:
  pull_request_target:
    branches:
      - main

env:
  NODE_VERSION: 14.x

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage --silent

      - name: Comment test coverage
        uses: raulanatol/jest-coverage-comment-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-existing-reports: true

      - name: Build
        run: yarn build
