name: Verify

on: [pull_request]

env:
  NODE_VERSION: 14.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Configure package manager
        run: |
          echo Configuring NPM_TOKEN globally for .npmrc
          npm config set '//registry.npmjs.org/:_authToken' ${{ env.NPM_TOKEN }}
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_READ_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --coverage

      - name: Comment test coverage
        uses: raulanatol/jest-coverage-comment-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-existing-reports: true

      # TODO: Re-enable once publishing is fixed
      # - name: Comment + Report Coverage
      #   uses: reside-eng/code-coverage-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn build
